process_names:
  - comm:
    - ntpd
    - loadmgr
    - procmgr
    - executor
    - sscheduler
    - dumpserver
    - restoreserver
    - mscheduler
    - lim
    - pim
    - sbatchd
    - mbschd
    - mbatchd